### ISSUE TITLE
Add suspend=y support to jvm debug

### ISSUE THREAD

**Issue by dwijnand** [paulp/sbt-extras#186]
This allows attaching a debugger to debug an early part of a program (instead of trying to race the JVM..).

@paulp I'm not sure how to implement this, basically add another flag or parse the `-jvm-debug` argument differently.. Do you have any suggestions, please?

**Comment by paulp** [comment]
`-jvm-debug` could be expressed as 
`-J-Xdebug -J-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=` and I'm pretty skeptical about adding more aliases, especially since this very ticket demonstrates the problem with bundling options and I think debugger attachers are a small minority of overall users. You could add a documentation page with example startup invocations which cover this case.

**Comment by paulp** [comment]
(Or to the script itself, e.g. `sbt -examples`)

**Comment by dwijnand** [comment]
Ok, no worries. :-)
